/**
 * RadioManager
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'radiomanagermodels/BroadcastEPGDay'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BroadcastEPGDay'));
  } else {
    // Browser globals (root is window)
    if (!root.radiomanager) {
      root.radiomanager = {};
    }
    root.radiomanager.EPGResults = factory(root.radiomanager.ApiClient, root.radiomanager.BroadcastEPGDay);
  }
}(this, function(ApiClient, BroadcastEPGDay) {
  'use strict';




  /**
   * The EPGResults model module.
   * @module radiomanagermodels/EPGResults
   * @version 2.0
   */

  /**
   * Constructs a new <code>EPGResults</code>.
   * @alias module:radiomanagermodels/EPGResults
   * @class
   * @param days {Array.<module:radiomanagermodels/BroadcastEPGDay>} 
   * @param nextPageUrl {String} 
   * @param prevPageUrl {String} 
   */
  var exports = function(days, nextPageUrl, prevPageUrl) {
    var _this = this;

    _this['days'] = days;
    _this['next_page_url'] = nextPageUrl;
    _this['prev_page_url'] = prevPageUrl;
  };

  /**
   * Constructs a <code>EPGResults</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:radiomanagermodels/EPGResults} obj Optional instance to populate.
   * @return {module:radiomanagermodels/EPGResults} The populated <code>EPGResults</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('days')) {
        obj['days'] = ApiClient.convertToType(data['days'], [BroadcastEPGDay]);
      }
      if (data.hasOwnProperty('next_page_url')) {
        obj['next_page_url'] = ApiClient.convertToType(data['next_page_url'], 'String');
      }
      if (data.hasOwnProperty('prev_page_url')) {
        obj['prev_page_url'] = ApiClient.convertToType(data['prev_page_url'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:radiomanagermodels/BroadcastEPGDay>} days
   */
  exports.prototype['days'] = undefined;
  /**
   * @member {String} next_page_url
   */
  exports.prototype['next_page_url'] = undefined;
  /**
   * @member {String} prev_page_url
   */
  exports.prototype['prev_page_url'] = undefined;


  /**
   * @return {Array.<module:radiomanagermodels/BroadcastEPGDay>}
   */
  exports.prototype.getDays = function() {
    return this['days'];
  }

  /**
   * @param {Array.<module:radiomanagermodels/BroadcastEPGDay>} days
   */
  exports.prototype.setDays = function(days) {
    this['days'] = days;
  }


  /**
   * @return {String}
   */
  exports.prototype.getNextPageUrl = function() {
    return this['next_page_url'];
  }

  /**
   * @param {String} nextPageUrl
   */
  exports.prototype.setNextPageUrl = function(nextPageUrl) {
    this['next_page_url'] = nextPageUrl;
  }


  /**
   * @return {String}
   */
  exports.prototype.getPrevPageUrl = function() {
    return this['prev_page_url'];
  }

  /**
   * @param {String} prevPageUrl
   */
  exports.prototype.setPrevPageUrl = function(prevPageUrl) {
    this['prev_page_url'] = prevPageUrl;
  }



  return exports;
}));


