/**
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'models/BroadcastDataInput', 'models/BroadcastResult', 'models/BroadcastResults', 'models/EPGResults', 'models/Forbidden', 'models/NotFound', 'models/PostSuccess', 'models/Success', 'models/TooManyRequests', 'models/UnprocessableEntity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../models/BroadcastDataInput'), require('../models/BroadcastResult'), require('../models/BroadcastResults'), require('../models/EPGResults'), require('../models/Forbidden'), require('../models/NotFound'), require('../models/PostSuccess'), require('../models/Success'), require('../models/TooManyRequests'), require('../models/UnprocessableEntity'));
  } else {
    // Browser globals (root is window)
    if (!root.radiomanager) {
      root.radiomanager = {};
    }
    root.radiomanager.BroadcastApi = factory(root.radiomanager.ApiClient, root.radiomanager.BroadcastDataInput, root.radiomanager.BroadcastResult, root.radiomanager.BroadcastResults, root.radiomanager.EPGResults, root.radiomanager.Forbidden, root.radiomanager.NotFound, root.radiomanager.PostSuccess, root.radiomanager.Success, root.radiomanager.TooManyRequests, root.radiomanager.UnprocessableEntity);
  }
}(this, function(ApiClient, BroadcastDataInput, BroadcastResult, BroadcastResults, EPGResults, Forbidden, NotFound, PostSuccess, Success, TooManyRequests, UnprocessableEntity) {
  'use strict';

  /**
   * Broadcast service.
   * @module radiomanager/BroadcastApi
   * @version 2.0
   */

  /**
   * Constructs a new BroadcastApi. 
   * @alias module:radiomanager/BroadcastApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Create broadcast.
     * Create broadcast.
     * @param {module:models/BroadcastDataInput} data Data **(Required)**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/PostSuccess} and HTTP response
     */
    this.createBroadcastWithHttpInfo = function(data) {
      var postBody = data;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling createBroadcast");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PostSuccess;
      return this.apiClient.callApi(
        '/broadcasts', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create broadcast.
     * Create broadcast.
     * @param {module:models/BroadcastDataInput} data Data **(Required)**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/PostSuccess}
     */
    this.createBroadcast = function(data) {
      return this.createBroadcastWithHttpInfo(data)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete broadcast by id
     * Delete broadcast by id
     * @param {Number} id ID of Broadcast **(Required)**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/Success} and HTTP response
     */
    this.deleteBroadcastByIdWithHttpInfo = function(id) {
      var postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteBroadcastById");
      }

      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Success;
      return this.apiClient.callApi(
        '/broadcasts/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete broadcast by id
     * Delete broadcast by id
     * @param {Number} id ID of Broadcast **(Required)**
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/Success}
     */
    this.deleteBroadcastById = function(id) {
      return this.deleteBroadcastByIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get broadcast by id
     * Get broadcast by id
     * @param {Number} id ID of Broadcast **(Required)**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.externalStationId Query on a different (content providing) station *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/BroadcastResult} and HTTP response
     */
    this.getBroadcastByIdWithHttpInfo = function(id, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getBroadcastById");
      }

      var pathParams = {
        'id': id
      };
      var queryParams = {
        '_external_station_id': opts['externalStationId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = BroadcastResult;
      return this.apiClient.callApi(
        '/broadcasts/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get broadcast by id
     * Get broadcast by id
     * @param {Number} id ID of Broadcast **(Required)**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.externalStationId Query on a different (content providing) station *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/BroadcastResult}
     */
    this.getBroadcastById = function(id, opts) {
      return this.getBroadcastByIdWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get current Broadcast
     * Get current Broadcast
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/BroadcastResult} and HTTP response
     */
    this.getCurrentBroadcastWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'withunpublished': opts['withunpublished'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = BroadcastResult;
      return this.apiClient.callApi(
        '/broadcasts/current', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get current Broadcast
     * Get current Broadcast
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/BroadcastResult}
     */
    this.getCurrentBroadcast = function(opts) {
      return this.getCurrentBroadcastWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get daily EPG
     * Get current Broadcast
     * @param {Object} opts Optional parameters
     * @param {Date} opts._date Date *(Optional)*
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/EPGResults} and HTTP response
     */
    this.getDailyEPGWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'date': opts['_date'],
        'withunpublished': opts['withunpublished'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = EPGResults;
      return this.apiClient.callApi(
        '/broadcasts/epg/daily', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get daily EPG
     * Get current Broadcast
     * @param {Object} opts Optional parameters
     * @param {Date} opts._date Date *(Optional)*
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/EPGResults}
     */
    this.getDailyEPG = function(opts) {
      return this.getDailyEPGWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get EPG by date
     * Get EPG by date
     * @param {Object} opts Optional parameters
     * @param {Date} opts._date Date *(Optional)*
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/EPGResults} and HTTP response
     */
    this.getEPGByDateWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'date': opts['_date'],
        'withunpublished': opts['withunpublished'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = EPGResults;
      return this.apiClient.callApi(
        '/broadcasts/epg', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get EPG by date
     * Get EPG by date
     * @param {Object} opts Optional parameters
     * @param {Date} opts._date Date *(Optional)*
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/EPGResults}
     */
    this.getEPGByDate = function(opts) {
      return this.getEPGByDateWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get next Broadcast
     * Get next Broadcast
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/BroadcastResult} and HTTP response
     */
    this.getNextBroadcastWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'withunpublished': opts['withunpublished'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = BroadcastResult;
      return this.apiClient.callApi(
        '/broadcasts/next', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get next Broadcast
     * Get next Broadcast
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/BroadcastResult}
     */
    this.getNextBroadcast = function(opts) {
      return this.getNextBroadcastWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get weekly EPG
     * Get weekly EPG
     * @param {Object} opts Optional parameters
     * @param {String} opts._date Date *(Optional)*
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/EPGResults} and HTTP response
     */
    this.getWeeklyEPGWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'date': opts['_date'],
        'withunpublished': opts['withunpublished'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = EPGResults;
      return this.apiClient.callApi(
        '/broadcasts/epg/weekly', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get weekly EPG
     * Get weekly EPG
     * @param {Object} opts Optional parameters
     * @param {String} opts._date Date *(Optional)*
     * @param {Boolean} opts.withunpublished Show Unpublished *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/EPGResults}
     */
    this.getWeeklyEPG = function(opts) {
      return this.getWeeklyEPGWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get all broadcasts.
     * List all broadcasts.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page Current page *(Optional)* (default to 1)
     * @param {Number} opts.programId Search on Program ID *(Optional)* `(Relation)`
     * @param {Number} opts.blockId Search on Block ID *(Optional)* `(Relation)`
     * @param {Number} opts.modelTypeId Search on ModelType ID *(Optional)* `(Relation)`
     * @param {Number} opts.tagId Search on Tag ID *(Optional)* `(Relation)`
     * @param {Number} opts.presenterId Search on Presenter ID *(Optional)* `(Relation)`
     * @param {Number} opts.genreId Search on Genre ID *(Optional)* `(Relation)`
     * @param {Number} opts.itemId Search on Item ID *(Optional)* `(Relation)`
     * @param {Date} opts.startMin Minimum start date *(Optional)*
     * @param {Date} opts.startMax Maximum start date *(Optional)*
     * @param {Number} opts.limit Results per page *(Optional)*
     * @param {String} opts.orderBy Field to order the results *(Optional)*
     * @param {module:models/String} opts.orderDirection Direction of ordering *(Optional)*
     * @param {Number} opts.externalStationId Query on a different (content providing) station *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/BroadcastResults} and HTTP response
     */
    this.listBroadcastsWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;

      var pathParams = {
      };
      var queryParams = {
        'page': opts['page'],
        'program_id': opts['programId'],
        'block_id': opts['blockId'],
        'model_type_id': opts['modelTypeId'],
        'tag_id': opts['tagId'],
        'presenter_id': opts['presenterId'],
        'genre_id': opts['genreId'],
        'item_id': opts['itemId'],
        'start-min': opts['startMin'],
        'start-max': opts['startMax'],
        'limit': opts['limit'],
        'order-by': opts['orderBy'],
        'order-direction': opts['orderDirection'],
        '_external_station_id': opts['externalStationId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = BroadcastResults;
      return this.apiClient.callApi(
        '/broadcasts', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get all broadcasts.
     * List all broadcasts.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page Current page *(Optional)* (default to 1)
     * @param {Number} opts.programId Search on Program ID *(Optional)* `(Relation)`
     * @param {Number} opts.blockId Search on Block ID *(Optional)* `(Relation)`
     * @param {Number} opts.modelTypeId Search on ModelType ID *(Optional)* `(Relation)`
     * @param {Number} opts.tagId Search on Tag ID *(Optional)* `(Relation)`
     * @param {Number} opts.presenterId Search on Presenter ID *(Optional)* `(Relation)`
     * @param {Number} opts.genreId Search on Genre ID *(Optional)* `(Relation)`
     * @param {Number} opts.itemId Search on Item ID *(Optional)* `(Relation)`
     * @param {Date} opts.startMin Minimum start date *(Optional)*
     * @param {Date} opts.startMax Maximum start date *(Optional)*
     * @param {Number} opts.limit Results per page *(Optional)*
     * @param {String} opts.orderBy Field to order the results *(Optional)*
     * @param {module:models/String} opts.orderDirection Direction of ordering *(Optional)*
     * @param {Number} opts.externalStationId Query on a different (content providing) station *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/BroadcastResults}
     */
    this.listBroadcasts = function(opts) {
      return this.listBroadcastsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Print broadcast by id with template
     * Print broadcast by id with template
     * @param {Number} id ID of Broadcast **(Required)**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.templateId Search on template ID *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link String} and HTTP response
     */
    this.printBroadcastByIdWithHttpInfo = function(id, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling printBroadcastById");
      }

      var pathParams = {
        'id': id
      };
      var queryParams = {
        'template_id': opts['templateId'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = 'String';
      return this.apiClient.callApi(
        '/broadcasts/print/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Print broadcast by id with template
     * Print broadcast by id with template
     * @param {Number} id ID of Broadcast **(Required)**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.templateId Search on template ID *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link String}
     */
    this.printBroadcastById = function(id, opts) {
      return this.printBroadcastByIdWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update broadcast by id
     * Update broadcast by id
     * @param {Number} id ID of Broadcast **(Required)**
     * @param {Object} opts Optional parameters
     * @param {module:models/BroadcastDataInput} opts.data Data *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:models/Success} and HTTP response
     */
    this.updateBroadcastByIDWithHttpInfo = function(id, opts) {
      opts = opts || {};
      var postBody = opts['data'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateBroadcastByID");
      }

      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['API-Key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Success;
      return this.apiClient.callApi(
        '/broadcasts/{id}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update broadcast by id
     * Update broadcast by id
     * @param {Number} id ID of Broadcast **(Required)**
     * @param {Object} opts Optional parameters
     * @param {module:models/BroadcastDataInput} opts.data Data *(Optional)*
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:models/Success}
     */
    this.updateBroadcastByID = function(id, opts) {
      return this.updateBroadcastByIDWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
