/**
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'models/BroadcastEPGResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BroadcastEPGResult'));
  } else {
    // Browser globals (root is window)
    if (!root.radiomanager) {
      root.radiomanager = {};
    }
    root.radiomanager.BroadcastEPGDay = factory(root.radiomanager.ApiClient, root.radiomanager.BroadcastEPGResult);
  }
}(this, function(ApiClient, BroadcastEPGResult) {
  'use strict';



  /**
   * The BroadcastEPGDay model module.
   * @module models/BroadcastEPGDay
   * @version 2.0
   */

  /**
   * Constructs a new <code>BroadcastEPGDay</code>.
   * @alias module:models/BroadcastEPGDay
   * @class
   * @param results {Array.<module:models/BroadcastEPGResult>} 
   */
  var exports = function(results) {
    var _this = this;

    _this['results'] = results;
  };

  /**
   * Constructs a <code>BroadcastEPGDay</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/BroadcastEPGDay} obj Optional instance to populate.
   * @return {module:models/BroadcastEPGDay} The populated <code>BroadcastEPGDay</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('day')) {
        obj['day'] = ApiClient.convertToType(data['day'], 'Date');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [BroadcastEPGResult]);
      }
    }
    return obj;
  }

  /**
   * @member {Date} day
   */
  exports.prototype['day'] = undefined;
  /**
   * @member {Array.<module:models/BroadcastEPGResult>} results
   */
  exports.prototype['results'] = undefined;


  /**
   * @return {Date}
   */
  exports.prototype.getDay = function() {
    return this['day'];
  }

  /**
   * @param {Date} day
   */
  exports.prototype.setDay = function(day) {
    this['day'] = day;
  }


  /**
   * @return {Array.<module:models/BroadcastEPGResult>}
   */
  exports.prototype.getResults = function() {
    return this['results'];
  }

  /**
   * @param {Array.<module:models/BroadcastEPGResult>} results
   */
  exports.prototype.setResults = function(results) {
    this['results'] = results;
  }



  return exports;
}));


