/**
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GroupOutputOnly model module.
 * @module models/GroupOutputOnly
 * @version 2.0
 */
class GroupOutputOnly {
    /**
     * Constructs a new <code>GroupOutputOnly</code>.
     * @alias module:models/GroupOutputOnly
     * @param id {Number} 
     * @param updatedAt {Date} 
     * @param createdAt {Date} 
     * @param deletedAt {Date} 
     */
    constructor(id, updatedAt, createdAt, deletedAt) { 
        
        GroupOutputOnly.initialize(this, id, updatedAt, createdAt, deletedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, updatedAt, createdAt, deletedAt) { 
        obj['id'] = id;
        obj['updated_at'] = updatedAt;
        obj['created_at'] = createdAt;
        obj['deleted_at'] = deletedAt;
    }

    /**
     * Constructs a <code>GroupOutputOnly</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/GroupOutputOnly} obj Optional instance to populate.
     * @return {module:models/GroupOutputOnly} The populated <code>GroupOutputOnly</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupOutputOnly();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GroupOutputOnly</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GroupOutputOnly</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GroupOutputOnly.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

/**
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {Number} id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {Date}
     */
    getUpdatedAt() {
        return this.updated_at;
    }

    /**
     * @param {Date} updatedAt
     */
    setUpdatedAt(updatedAt) {
        this['updated_at'] = updatedAt;
    }
/**
     * @return {Date}
     */
    getCreatedAt() {
        return this.created_at;
    }

    /**
     * @param {Date} createdAt
     */
    setCreatedAt(createdAt) {
        this['created_at'] = createdAt;
    }
/**
     * @return {Date}
     */
    getDeletedAt() {
        return this.deleted_at;
    }

    /**
     * @param {Date} deletedAt
     */
    setDeletedAt(deletedAt) {
        this['deleted_at'] = deletedAt;
    }

}

GroupOutputOnly.RequiredProperties = ["id", "updated_at", "created_at", "deleted_at"];

/**
 * @member {Number} id
 */
GroupOutputOnly.prototype['id'] = undefined;

/**
 * @member {Date} updated_at
 */
GroupOutputOnly.prototype['updated_at'] = undefined;

/**
 * @member {Date} created_at
 */
GroupOutputOnly.prototype['created_at'] = undefined;

/**
 * @member {Date} deleted_at
 */
GroupOutputOnly.prototype['deleted_at'] = undefined;






export default GroupOutputOnly;

