/**
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse422 model module.
 * @module models/InlineResponse422
 * @version 2.0
 */
class InlineResponse422 {
    /**
     * Constructs a new <code>InlineResponse422</code>.
     * @alias module:models/InlineResponse422
     */
    constructor() { 
        
        InlineResponse422.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse422</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/InlineResponse422} obj Optional instance to populate.
     * @return {module:models/InlineResponse422} The populated <code>InlineResponse422</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse422();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], Object);
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InlineResponse422</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InlineResponse422</code>.
     */
    static validateJSON(data) {

        return true;
    }

/**
     * Returns A key/value list that displays all the invalid properties.
     * @return {Object}
     */
    getErrors() {
        return this.errors;
    }

    /**
     * Sets A key/value list that displays all the invalid properties.
     * @param {Object} errors A key/value list that displays all the invalid properties.
     */
    setErrors(errors) {
        this['errors'] = errors;
    }
/**
     * Returns Corresponding HTTP Response Status Code
     * @return {Number}
     */
    getStatusCode() {
        return this.statusCode;
    }

    /**
     * Sets Corresponding HTTP Response Status Code
     * @param {Number} statusCode Corresponding HTTP Response Status Code
     */
    setStatusCode(statusCode) {
        this['statusCode'] = statusCode;
    }

}



/**
 * A key/value list that displays all the invalid properties.
 * @member {Object} errors
 */
InlineResponse422.prototype['errors'] = undefined;

/**
 * Corresponding HTTP Response Status Code
 * @member {Number} statusCode
 */
InlineResponse422.prototype['statusCode'] = undefined;






export default InlineResponse422;

