/**
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'models/BlockRelationsBroadcast', 'models/BroadcastRelationsModelType', 'models/Item', 'models/ItemOutputOnly', 'models/ItemRelations', 'models/ItemRelationsBlock', 'models/ItemRelationsCampaign', 'models/ItemRelationsContacts', 'models/ItemRelationsProgram', 'models/ItemRelationsTags'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BlockRelationsBroadcast'), require('./BroadcastRelationsModelType'), require('./Item'), require('./ItemOutputOnly'), require('./ItemRelations'), require('./ItemRelationsBlock'), require('./ItemRelationsCampaign'), require('./ItemRelationsContacts'), require('./ItemRelationsProgram'), require('./ItemRelationsTags'));
  } else {
    // Browser globals (root is window)
    if (!root.radiomanager) {
      root.radiomanager = {};
    }
    root.radiomanager.ItemResult = factory(root.radiomanager.ApiClient, root.radiomanager.BlockRelationsBroadcast, root.radiomanager.BroadcastRelationsModelType, root.radiomanager.Item, root.radiomanager.ItemOutputOnly, root.radiomanager.ItemRelations, root.radiomanager.ItemRelationsBlock, root.radiomanager.ItemRelationsCampaign, root.radiomanager.ItemRelationsContacts, root.radiomanager.ItemRelationsProgram, root.radiomanager.ItemRelationsTags);
  }
}(this, function(ApiClient, BlockRelationsBroadcast, BroadcastRelationsModelType, Item, ItemOutputOnly, ItemRelations, ItemRelationsBlock, ItemRelationsCampaign, ItemRelationsContacts, ItemRelationsProgram, ItemRelationsTags) {
  'use strict';



  /**
   * The ItemResult model module.
   * @module models/ItemResult
   * @version 2.0
   */

  /**
   * Constructs a new <code>ItemResult</code>.
   * @alias module:models/ItemResult
   * @class
   * @implements module:models/ItemOutputOnly
   * @implements module:models/Item
   * @implements module:models/ItemRelations
   * @param modelTypeId {Number} 
   */
  var exports = function(modelTypeId) {
    var _this = this;

    ItemOutputOnly.call(_this);
    Item.call(_this, modelTypeId);
    ItemRelations.call(_this);
    _this['model_type_id'] = modelTypeId;
  };

  /**
   * Constructs a <code>ItemResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/ItemResult} obj Optional instance to populate.
   * @return {module:models/ItemResult} The populated <code>ItemResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ItemOutputOnly.constructFromObject(data, obj);
      Item.constructFromObject(data, obj);
      ItemRelations.constructFromObject(data, obj);
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('deleted_at')) {
        obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
      }
      if (data.hasOwnProperty('data_modified')) {
        obj['data_modified'] = ApiClient.convertToType(data['data_modified'], 'Number');
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Number');
      }
      if (data.hasOwnProperty('templateblock_id')) {
        obj['templateblock_id'] = ApiClient.convertToType(data['templateblock_id'], 'Number');
      }
      if (data.hasOwnProperty('templateitem_id')) {
        obj['templateitem_id'] = ApiClient.convertToType(data['templateitem_id'], 'Number');
      }
      if (data.hasOwnProperty('_external_station_id')) {
        obj['_external_station_id'] = ApiClient.convertToType(data['_external_station_id'], 'Number');
      }
      if (data.hasOwnProperty('model_type_id')) {
        obj['model_type_id'] = ApiClient.convertToType(data['model_type_id'], 'Number');
      }
      if (data.hasOwnProperty('block_id')) {
        obj['block_id'] = ApiClient.convertToType(data['block_id'], 'Number');
      }
      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('field_values')) {
        obj['field_values'] = ApiClient.convertToType(data['field_values'], Object);
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('import')) {
        obj['import'] = ApiClient.convertToType(data['import'], 'Number');
      }
      if (data.hasOwnProperty('campaign_id')) {
        obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'Number');
      }
      if (data.hasOwnProperty('recommended')) {
        obj['recommended'] = ApiClient.convertToType(data['recommended'], 'Boolean');
      }
      if (data.hasOwnProperty('station_draft_id')) {
        obj['station_draft_id'] = ApiClient.convertToType(data['station_draft_id'], 'Number');
      }
      if (data.hasOwnProperty('program_draft_id')) {
        obj['program_draft_id'] = ApiClient.convertToType(data['program_draft_id'], 'Number');
      }
      if (data.hasOwnProperty('user_draft_id')) {
        obj['user_draft_id'] = ApiClient.convertToType(data['user_draft_id'], 'Number');
      }
      if (data.hasOwnProperty('static_start')) {
        obj['static_start'] = ApiClient.convertToType(data['static_start'], 'Boolean');
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = ApiClient.convertToType(data['details'], 'String');
      }
      if (data.hasOwnProperty('block')) {
        obj['block'] = ItemRelationsBlock.constructFromObject(data['block']);
      }
      if (data.hasOwnProperty('broadcast')) {
        obj['broadcast'] = BlockRelationsBroadcast.constructFromObject(data['broadcast']);
      }
      if (data.hasOwnProperty('program')) {
        obj['program'] = ItemRelationsProgram.constructFromObject(data['program']);
      }
      if (data.hasOwnProperty('contacts')) {
        obj['contacts'] = ItemRelationsContacts.constructFromObject(data['contacts']);
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ItemRelationsTags.constructFromObject(data['tags']);
      }
      if (data.hasOwnProperty('campaign')) {
        obj['campaign'] = ItemRelationsCampaign.constructFromObject(data['campaign']);
      }
      if (data.hasOwnProperty('model_type')) {
        obj['model_type'] = BroadcastRelationsModelType.constructFromObject(data['model_type']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Date} deleted_at
   */
  exports.prototype['deleted_at'] = undefined;
  /**
   * @member {Number} data_modified
   */
  exports.prototype['data_modified'] = undefined;
  /**
   * @member {Number} order
   */
  exports.prototype['order'] = undefined;
  /**
   * @member {Number} templateblock_id
   */
  exports.prototype['templateblock_id'] = undefined;
  /**
   * @member {Number} templateitem_id
   */
  exports.prototype['templateitem_id'] = undefined;
  /**
   * @member {Number} _external_station_id
   */
  exports.prototype['_external_station_id'] = undefined;
  /**
   * @member {Number} model_type_id
   */
  exports.prototype['model_type_id'] = undefined;
  /**
   * @member {Number} block_id
   */
  exports.prototype['block_id'] = undefined;
  /**
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * @member {Object} field_values
   */
  exports.prototype['field_values'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {Date} start
   */
  exports.prototype['start'] = undefined;
  /**
   * @member {module:models/ItemResult.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Number} import
   */
  exports.prototype['import'] = undefined;
  /**
   * @member {Number} campaign_id
   */
  exports.prototype['campaign_id'] = undefined;
  /**
   * @member {Boolean} recommended
   */
  exports.prototype['recommended'] = undefined;
  /**
   * @member {Number} station_draft_id
   */
  exports.prototype['station_draft_id'] = undefined;
  /**
   * @member {Number} program_draft_id
   */
  exports.prototype['program_draft_id'] = undefined;
  /**
   * @member {Number} user_draft_id
   */
  exports.prototype['user_draft_id'] = undefined;
  /**
   * @member {Boolean} static_start
   */
  exports.prototype['static_start'] = undefined;
  /**
   * @member {String} details
   */
  exports.prototype['details'] = undefined;
  /**
   * @member {module:models/ItemRelationsBlock} block
   */
  exports.prototype['block'] = undefined;
  /**
   * @member {module:models/BlockRelationsBroadcast} broadcast
   */
  exports.prototype['broadcast'] = undefined;
  /**
   * @member {module:models/ItemRelationsProgram} program
   */
  exports.prototype['program'] = undefined;
  /**
   * @member {module:models/ItemRelationsContacts} contacts
   */
  exports.prototype['contacts'] = undefined;
  /**
   * @member {module:models/ItemRelationsTags} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {module:models/ItemRelationsCampaign} campaign
   */
  exports.prototype['campaign'] = undefined;
  /**
   * @member {module:models/BroadcastRelationsModelType} model_type
   */
  exports.prototype['model_type'] = undefined;

  // Implement ItemOutputOnly interface:
  /**
   * @member {Number} id
   */
exports.prototype['id'] = undefined;

  /**
   * @member {Date} updated_at
   */
exports.prototype['updated_at'] = undefined;

  /**
   * @member {Date} created_at
   */
exports.prototype['created_at'] = undefined;

  /**
   * @member {Date} deleted_at
   */
exports.prototype['deleted_at'] = undefined;

  /**
   * @member {Number} data_modified
   */
exports.prototype['data_modified'] = undefined;

  /**
   * @member {Number} order
   */
exports.prototype['order'] = undefined;

  /**
   * @member {Number} templateblock_id
   */
exports.prototype['templateblock_id'] = undefined;

  /**
   * @member {Number} templateitem_id
   */
exports.prototype['templateitem_id'] = undefined;

  /**
   * @member {Number} _external_station_id
   */
exports.prototype['_external_station_id'] = undefined;

  // Implement Item interface:
  /**
   * @member {Number} model_type_id
   */
exports.prototype['model_type_id'] = undefined;

  /**
   * @member {Number} block_id
   */
exports.prototype['block_id'] = undefined;

  /**
   * @member {String} external_id
   */
exports.prototype['external_id'] = undefined;

  /**
   * @member {Object} field_values
   */
exports.prototype['field_values'] = undefined;

  /**
   * @member {String} title
   */
exports.prototype['title'] = undefined;

  /**
   * @member {Number} duration
   */
exports.prototype['duration'] = undefined;

  /**
   * @member {Date} start
   */
exports.prototype['start'] = undefined;

  /**
   * @member {module:models/Item.StatusEnum} status
   */
exports.prototype['status'] = undefined;

  /**
   * @member {Number} import
   */
exports.prototype['import'] = undefined;

  /**
   * @member {Number} campaign_id
   */
exports.prototype['campaign_id'] = undefined;

  /**
   * @member {Boolean} recommended
   */
exports.prototype['recommended'] = undefined;

  /**
   * @member {Number} station_draft_id
   */
exports.prototype['station_draft_id'] = undefined;

  /**
   * @member {Number} program_draft_id
   */
exports.prototype['program_draft_id'] = undefined;

  /**
   * @member {Number} user_draft_id
   */
exports.prototype['user_draft_id'] = undefined;

  /**
   * @member {Boolean} static_start
   */
exports.prototype['static_start'] = undefined;

  /**
   * @member {String} details
   */
exports.prototype['details'] = undefined;

  // Implement ItemRelations interface:
  /**
   * @member {module:models/ItemRelationsBlock} block
   */
exports.prototype['block'] = undefined;

  /**
   * @member {module:models/BlockRelationsBroadcast} broadcast
   */
exports.prototype['broadcast'] = undefined;

  /**
   * @member {module:models/ItemRelationsProgram} program
   */
exports.prototype['program'] = undefined;

  /**
   * @member {module:models/ItemRelationsContacts} contacts
   */
exports.prototype['contacts'] = undefined;

  /**
   * @member {module:models/ItemRelationsTags} tags
   */
exports.prototype['tags'] = undefined;

  /**
   * @member {module:models/ItemRelationsCampaign} campaign
   */
exports.prototype['campaign'] = undefined;

  /**
   * @member {module:models/BroadcastRelationsModelType} model_type
   */
exports.prototype['model_type'] = undefined;


  /**
   * @return {Number}
   */
  exports.prototype.getId = function() {
    return this['id'];
  }

  /**
   * @param {Number} id
   */
  exports.prototype.setId = function(id) {
    this['id'] = id;
  }


  /**
   * @return {Date}
   */
  exports.prototype.getUpdatedAt = function() {
    return this['updated_at'];
  }

  /**
   * @param {Date} updatedAt
   */
  exports.prototype.setUpdatedAt = function(updatedAt) {
    this['updated_at'] = updatedAt;
  }


  /**
   * @return {Date}
   */
  exports.prototype.getCreatedAt = function() {
    return this['created_at'];
  }

  /**
   * @param {Date} createdAt
   */
  exports.prototype.setCreatedAt = function(createdAt) {
    this['created_at'] = createdAt;
  }


  /**
   * @return {Date}
   */
  exports.prototype.getDeletedAt = function() {
    return this['deleted_at'];
  }

  /**
   * @param {Date} deletedAt
   */
  exports.prototype.setDeletedAt = function(deletedAt) {
    this['deleted_at'] = deletedAt;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getDataModified = function() {
    return this['data_modified'];
  }

  /**
   * @param {Number} dataModified
   */
  exports.prototype.setDataModified = function(dataModified) {
    this['data_modified'] = dataModified;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getOrder = function() {
    return this['order'];
  }

  /**
   * @param {Number} order
   */
  exports.prototype.setOrder = function(order) {
    this['order'] = order;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getTemplateblockId = function() {
    return this['templateblock_id'];
  }

  /**
   * @param {Number} templateblockId
   */
  exports.prototype.setTemplateblockId = function(templateblockId) {
    this['templateblock_id'] = templateblockId;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getTemplateitemId = function() {
    return this['templateitem_id'];
  }

  /**
   * @param {Number} templateitemId
   */
  exports.prototype.setTemplateitemId = function(templateitemId) {
    this['templateitem_id'] = templateitemId;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getExternalStationId = function() {
    return this['_external_station_id'];
  }

  /**
   * @param {Number} externalStationId
   */
  exports.prototype.setExternalStationId = function(externalStationId) {
    this['_external_station_id'] = externalStationId;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getModelTypeId = function() {
    return this['model_type_id'];
  }

  /**
   * @param {Number} modelTypeId
   */
  exports.prototype.setModelTypeId = function(modelTypeId) {
    this['model_type_id'] = modelTypeId;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getBlockId = function() {
    return this['block_id'];
  }

  /**
   * @param {Number} blockId
   */
  exports.prototype.setBlockId = function(blockId) {
    this['block_id'] = blockId;
  }


  /**
   * @return {String}
   */
  exports.prototype.getExternalId = function() {
    return this['external_id'];
  }

  /**
   * @param {String} externalId
   */
  exports.prototype.setExternalId = function(externalId) {
    this['external_id'] = externalId;
  }


  /**
   * @return {Object}
   */
  exports.prototype.getFieldValues = function() {
    return this['field_values'];
  }

  /**
   * @param {Object} fieldValues
   */
  exports.prototype.setFieldValues = function(fieldValues) {
    this['field_values'] = fieldValues;
  }


  /**
   * @return {String}
   */
  exports.prototype.getTitle = function() {
    return this['title'];
  }

  /**
   * @param {String} title
   */
  exports.prototype.setTitle = function(title) {
    this['title'] = title;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getDuration = function() {
    return this['duration'];
  }

  /**
   * @param {Number} duration
   */
  exports.prototype.setDuration = function(duration) {
    this['duration'] = duration;
  }


  /**
   * @return {Date}
   */
  exports.prototype.getStart = function() {
    return this['start'];
  }

  /**
   * @param {Date} start
   */
  exports.prototype.setStart = function(start) {
    this['start'] = start;
  }


  /**
   * @return {module:models/ItemResult.StatusEnum}
   */
  exports.prototype.getStatus = function() {
    return this['status'];
  }

  /**
   * @param {module:models/ItemResult.StatusEnum} status
   */
  exports.prototype.setStatus = function(status) {
    this['status'] = status;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getImport = function() {
    return this['import'];
  }

  /**
   * @param {Number} _import
   */
  exports.prototype.setImport = function(_import) {
    this['import'] = _import;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getCampaignId = function() {
    return this['campaign_id'];
  }

  /**
   * @param {Number} campaignId
   */
  exports.prototype.setCampaignId = function(campaignId) {
    this['campaign_id'] = campaignId;
  }


  /**
   * @return {Boolean}
   */
  exports.prototype.getRecommended = function() {
    return this['recommended'];
  }

  /**
   * @param {Boolean} recommended
   */
  exports.prototype.setRecommended = function(recommended) {
    this['recommended'] = recommended;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getStationDraftId = function() {
    return this['station_draft_id'];
  }

  /**
   * @param {Number} stationDraftId
   */
  exports.prototype.setStationDraftId = function(stationDraftId) {
    this['station_draft_id'] = stationDraftId;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getProgramDraftId = function() {
    return this['program_draft_id'];
  }

  /**
   * @param {Number} programDraftId
   */
  exports.prototype.setProgramDraftId = function(programDraftId) {
    this['program_draft_id'] = programDraftId;
  }


  /**
   * @return {Number}
   */
  exports.prototype.getUserDraftId = function() {
    return this['user_draft_id'];
  }

  /**
   * @param {Number} userDraftId
   */
  exports.prototype.setUserDraftId = function(userDraftId) {
    this['user_draft_id'] = userDraftId;
  }


  /**
   * @return {Boolean}
   */
  exports.prototype.getStaticStart = function() {
    return this['static_start'];
  }

  /**
   * @param {Boolean} staticStart
   */
  exports.prototype.setStaticStart = function(staticStart) {
    this['static_start'] = staticStart;
  }


  /**
   * @return {String}
   */
  exports.prototype.getDetails = function() {
    return this['details'];
  }

  /**
   * @param {String} details
   */
  exports.prototype.setDetails = function(details) {
    this['details'] = details;
  }


  /**
   * @return {module:models/ItemRelationsBlock}
   */
  exports.prototype.getBlock = function() {
    return this['block'];
  }

  /**
   * @param {module:models/ItemRelationsBlock} block
   */
  exports.prototype.setBlock = function(block) {
    this['block'] = block;
  }


  /**
   * @return {module:models/BlockRelationsBroadcast}
   */
  exports.prototype.getBroadcast = function() {
    return this['broadcast'];
  }

  /**
   * @param {module:models/BlockRelationsBroadcast} broadcast
   */
  exports.prototype.setBroadcast = function(broadcast) {
    this['broadcast'] = broadcast;
  }


  /**
   * @return {module:models/ItemRelationsProgram}
   */
  exports.prototype.getProgram = function() {
    return this['program'];
  }

  /**
   * @param {module:models/ItemRelationsProgram} program
   */
  exports.prototype.setProgram = function(program) {
    this['program'] = program;
  }


  /**
   * @return {module:models/ItemRelationsContacts}
   */
  exports.prototype.getContacts = function() {
    return this['contacts'];
  }

  /**
   * @param {module:models/ItemRelationsContacts} contacts
   */
  exports.prototype.setContacts = function(contacts) {
    this['contacts'] = contacts;
  }


  /**
   * @return {module:models/ItemRelationsTags}
   */
  exports.prototype.getTags = function() {
    return this['tags'];
  }

  /**
   * @param {module:models/ItemRelationsTags} tags
   */
  exports.prototype.setTags = function(tags) {
    this['tags'] = tags;
  }


  /**
   * @return {module:models/ItemRelationsCampaign}
   */
  exports.prototype.getCampaign = function() {
    return this['campaign'];
  }

  /**
   * @param {module:models/ItemRelationsCampaign} campaign
   */
  exports.prototype.setCampaign = function(campaign) {
    this['campaign'] = campaign;
  }


  /**
   * @return {module:models/BroadcastRelationsModelType}
   */
  exports.prototype.getModelType = function() {
    return this['model_type'];
  }

  /**
   * @param {module:models/BroadcastRelationsModelType} modelType
   */
  exports.prototype.setModelType = function(modelType) {
    this['model_type'] = modelType;
  }


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "scheduled"
     * @const
     */
    "scheduled": "scheduled",
    /**
     * value: "playing"
     * @const
     */
    "playing": "playing",
    /**
     * value: "played"
     * @const
     */
    "played": "played"  };


  return exports;
}));


