/**
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OrderDirection.
* @enum {}
* @readonly
*/
export default class OrderDirection {
    
        /**
         * value: "asc"
         * @const
         */
        "asc" = "asc";

    
        /**
         * value: "desc"
         * @const
         */
        "desc" = "desc";

    

    /**
    * Returns a <code>OrderDirection</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/OrderDirection} The enum <code>OrderDirection</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

