/**
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'models/Presenter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Presenter'));
  } else {
    // Browser globals (root is window)
    if (!root.radiomanager) {
      root.radiomanager = {};
    }
    root.radiomanager.PresenterDataInput = factory(root.radiomanager.ApiClient, root.radiomanager.Presenter);
  }
}(this, function(ApiClient, Presenter) {
  'use strict';



  /**
   * The PresenterDataInput model module.
   * @module models/PresenterDataInput
   * @version 2.0
   */

  /**
   * Constructs a new <code>PresenterDataInput</code>.
   * @alias module:models/PresenterDataInput
   * @class
   * @extends module:models/Presenter
   * @implements module:models/Presenter
   * @param modelTypeId {Number} 
   */
  var exports = function(modelTypeId) {
    var _this = this;

    Presenter.call(_this, modelTypeId);
  };

  /**
   * Constructs a <code>PresenterDataInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/PresenterDataInput} obj Optional instance to populate.
   * @return {module:models/PresenterDataInput} The populated <code>PresenterDataInput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      Presenter.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(Presenter.prototype);
  exports.prototype.constructor = exports;


  // Implement Presenter interface:
  /**
   * @member {Number} model_type_id
   */
exports.prototype['model_type_id'] = undefined;

  /**
   * @member {Object} field_values
   */
exports.prototype['field_values'] = undefined;

  /**
   * @member {String} firstname
   */
exports.prototype['firstname'] = undefined;

  /**
   * @member {String} lastname
   */
exports.prototype['lastname'] = undefined;

  /**
   * @member {Boolean} active
   */
exports.prototype['active'] = undefined;

  /**
   * @member {String} name
   */
exports.prototype['name'] = undefined;



  return exports;
}));


