/**
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Presenter from './Presenter';
import PresenterOutputOnly from './PresenterOutputOnly';
import PresenterRelations from './PresenterRelations';
import PresenterRelationsBroadcasts from './PresenterRelationsBroadcasts';
import PresenterRelationsModelType from './PresenterRelationsModelType';
import PresenterRelationsPrograms from './PresenterRelationsPrograms';

/**
 * The PresenterResult model module.
 * @module models/PresenterResult
 * @version 2.0
 */
class PresenterResult {
    /**
     * Constructs a new <code>PresenterResult</code>.
     * @alias module:models/PresenterResult
     * @implements module:models/PresenterOutputOnly
     * @implements module:models/Presenter
     * @implements module:models/PresenterRelations
     * @param id {Number} 
     * @param updatedAt {Date} 
     * @param createdAt {Date} 
     * @param deletedAt {Date} 
     * @param modelTypeId {Number} 
     */
    constructor(id, updatedAt, createdAt, deletedAt, modelTypeId) { 
        PresenterOutputOnly.initialize(this, id, updatedAt, createdAt, deletedAt);Presenter.initialize(this, modelTypeId);PresenterRelations.initialize(this);
        PresenterResult.initialize(this, id, updatedAt, createdAt, deletedAt, modelTypeId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, updatedAt, createdAt, deletedAt, modelTypeId) { 
        obj['id'] = id;
        obj['updated_at'] = updatedAt;
        obj['created_at'] = createdAt;
        obj['deleted_at'] = deletedAt;
        obj['model_type_id'] = modelTypeId;
    }

    /**
     * Constructs a <code>PresenterResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/PresenterResult} obj Optional instance to populate.
     * @return {module:models/PresenterResult} The populated <code>PresenterResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PresenterResult();
            PresenterOutputOnly.constructFromObject(data, obj);
            Presenter.constructFromObject(data, obj);
            PresenterRelations.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('_external_station_id')) {
                obj['_external_station_id'] = ApiClient.convertToType(data['_external_station_id'], 'Number');
            }
            if (data.hasOwnProperty('model_type_id')) {
                obj['model_type_id'] = ApiClient.convertToType(data['model_type_id'], 'Number');
            }
            if (data.hasOwnProperty('field_values')) {
                obj['field_values'] = ApiClient.convertToType(data['field_values'], Object);
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('programs')) {
                obj['programs'] = PresenterRelationsPrograms.constructFromObject(data['programs']);
            }
            if (data.hasOwnProperty('broadcasts')) {
                obj['broadcasts'] = PresenterRelationsBroadcasts.constructFromObject(data['broadcasts']);
            }
            if (data.hasOwnProperty('model_type')) {
                obj['model_type'] = PresenterRelationsModelType.constructFromObject(data['model_type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PresenterResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PresenterResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PresenterResult.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['firstname'] && !(typeof data['firstname'] === 'string' || data['firstname'] instanceof String)) {
            throw new Error("Expected the field `firstname` to be a primitive type in the JSON string but got " + data['firstname']);
        }
        // ensure the json data is a string
        if (data['lastname'] && !(typeof data['lastname'] === 'string' || data['lastname'] instanceof String)) {
            throw new Error("Expected the field `lastname` to be a primitive type in the JSON string but got " + data['lastname']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `programs`
        if (data['programs']) { // data not null
          PresenterRelationsPrograms.validateJSON(data['programs']);
        }
        // validate the optional field `broadcasts`
        if (data['broadcasts']) { // data not null
          PresenterRelationsBroadcasts.validateJSON(data['broadcasts']);
        }
        // validate the optional field `model_type`
        if (data['model_type']) { // data not null
          PresenterRelationsModelType.validateJSON(data['model_type']);
        }

        return true;
    }

/**
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {Number} id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {Date}
     */
    getUpdatedAt() {
        return this.updated_at;
    }

    /**
     * @param {Date} updatedAt
     */
    setUpdatedAt(updatedAt) {
        this['updated_at'] = updatedAt;
    }
/**
     * @return {Date}
     */
    getCreatedAt() {
        return this.created_at;
    }

    /**
     * @param {Date} createdAt
     */
    setCreatedAt(createdAt) {
        this['created_at'] = createdAt;
    }
/**
     * @return {Date}
     */
    getDeletedAt() {
        return this.deleted_at;
    }

    /**
     * @param {Date} deletedAt
     */
    setDeletedAt(deletedAt) {
        this['deleted_at'] = deletedAt;
    }
/**
     * @return {Number}
     */
    getExternalStationId() {
        return this._external_station_id;
    }

    /**
     * @param {Number} externalStationId
     */
    setExternalStationId(externalStationId) {
        this['_external_station_id'] = externalStationId;
    }
/**
     * @return {Number}
     */
    getModelTypeId() {
        return this.model_type_id;
    }

    /**
     * @param {Number} modelTypeId
     */
    setModelTypeId(modelTypeId) {
        this['model_type_id'] = modelTypeId;
    }
/**
     * @return {Object}
     */
    getFieldValues() {
        return this.field_values;
    }

    /**
     * @param {Object} fieldValues
     */
    setFieldValues(fieldValues) {
        this['field_values'] = fieldValues;
    }
/**
     * @return {String}
     */
    getFirstname() {
        return this.firstname;
    }

    /**
     * @param {String} firstname
     */
    setFirstname(firstname) {
        this['firstname'] = firstname;
    }
/**
     * @return {String}
     */
    getLastname() {
        return this.lastname;
    }

    /**
     * @param {String} lastname
     */
    setLastname(lastname) {
        this['lastname'] = lastname;
    }
/**
     * @return {Boolean}
     */
    getActive() {
        return this.active;
    }

    /**
     * @param {Boolean} active
     */
    setActive(active) {
        this['active'] = active;
    }
/**
     * @return {String}
     */
    getName() {
        return this.name;
    }

    /**
     * @param {String} name
     */
    setName(name) {
        this['name'] = name;
    }
/**
     * @return {module:models/PresenterRelationsPrograms}
     */
    getPrograms() {
        return this.programs;
    }

    /**
     * @param {module:models/PresenterRelationsPrograms} programs
     */
    setPrograms(programs) {
        this['programs'] = programs;
    }
/**
     * @return {module:models/PresenterRelationsBroadcasts}
     */
    getBroadcasts() {
        return this.broadcasts;
    }

    /**
     * @param {module:models/PresenterRelationsBroadcasts} broadcasts
     */
    setBroadcasts(broadcasts) {
        this['broadcasts'] = broadcasts;
    }
/**
     * @return {module:models/PresenterRelationsModelType}
     */
    getModelType() {
        return this.model_type;
    }

    /**
     * @param {module:models/PresenterRelationsModelType} modelType
     */
    setModelType(modelType) {
        this['model_type'] = modelType;
    }

}

PresenterResult.RequiredProperties = ["id", "updated_at", "created_at", "deleted_at", "model_type_id"];

/**
 * @member {Number} id
 */
PresenterResult.prototype['id'] = undefined;

/**
 * @member {Date} updated_at
 */
PresenterResult.prototype['updated_at'] = undefined;

/**
 * @member {Date} created_at
 */
PresenterResult.prototype['created_at'] = undefined;

/**
 * @member {Date} deleted_at
 */
PresenterResult.prototype['deleted_at'] = undefined;

/**
 * @member {Number} _external_station_id
 */
PresenterResult.prototype['_external_station_id'] = undefined;

/**
 * @member {Number} model_type_id
 */
PresenterResult.prototype['model_type_id'] = undefined;

/**
 * @member {Object} field_values
 */
PresenterResult.prototype['field_values'] = undefined;

/**
 * @member {String} firstname
 */
PresenterResult.prototype['firstname'] = undefined;

/**
 * @member {String} lastname
 */
PresenterResult.prototype['lastname'] = undefined;

/**
 * @member {Boolean} active
 */
PresenterResult.prototype['active'] = undefined;

/**
 * @member {String} name
 */
PresenterResult.prototype['name'] = undefined;

/**
 * @member {module:models/PresenterRelationsPrograms} programs
 */
PresenterResult.prototype['programs'] = undefined;

/**
 * @member {module:models/PresenterRelationsBroadcasts} broadcasts
 */
PresenterResult.prototype['broadcasts'] = undefined;

/**
 * @member {module:models/PresenterRelationsModelType} model_type
 */
PresenterResult.prototype['model_type'] = undefined;


// Implement PresenterOutputOnly interface:
/**
 * @member {Number} id
 */
PresenterOutputOnly.prototype['id'] = undefined;
/**
 * @member {Date} updated_at
 */
PresenterOutputOnly.prototype['updated_at'] = undefined;
/**
 * @member {Date} created_at
 */
PresenterOutputOnly.prototype['created_at'] = undefined;
/**
 * @member {Date} deleted_at
 */
PresenterOutputOnly.prototype['deleted_at'] = undefined;
/**
 * @member {Number} _external_station_id
 */
PresenterOutputOnly.prototype['_external_station_id'] = undefined;
// Implement Presenter interface:
/**
 * @member {Number} model_type_id
 */
Presenter.prototype['model_type_id'] = undefined;
/**
 * @member {Object} field_values
 */
Presenter.prototype['field_values'] = undefined;
/**
 * @member {String} firstname
 */
Presenter.prototype['firstname'] = undefined;
/**
 * @member {String} lastname
 */
Presenter.prototype['lastname'] = undefined;
/**
 * @member {Boolean} active
 */
Presenter.prototype['active'] = undefined;
/**
 * @member {String} name
 */
Presenter.prototype['name'] = undefined;
// Implement PresenterRelations interface:
/**
 * @member {module:models/PresenterRelationsPrograms} programs
 */
PresenterRelations.prototype['programs'] = undefined;
/**
 * @member {module:models/PresenterRelationsBroadcasts} broadcasts
 */
PresenterRelations.prototype['broadcasts'] = undefined;
/**
 * @member {module:models/PresenterRelationsModelType} model_type
 */
PresenterRelations.prototype['model_type'] = undefined;




export default PresenterResult;

