/**
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.radiomanager) {
      root.radiomanager = {};
    }
    root.radiomanager.ProgramInputOnlyAllOf = factory(root.radiomanager.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ProgramInputOnlyAllOf model module.
   * @module models/ProgramInputOnlyAllOf
   * @version 2.0
   */

  /**
   * Constructs a new <code>ProgramInputOnlyAllOf</code>.
   * @alias module:models/ProgramInputOnlyAllOf
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ProgramInputOnlyAllOf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/ProgramInputOnlyAllOf} obj Optional instance to populate.
   * @return {module:models/ProgramInputOnlyAllOf} The populated <code>ProgramInputOnlyAllOf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], ['Number']);
      }
      if (data.hasOwnProperty('presenters')) {
        obj['presenters'] = ApiClient.convertToType(data['presenters'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<Number>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {Array.<Number>} presenters
   */
  exports.prototype['presenters'] = undefined;


  /**
   * @return {Array.<Number>}
   */
  exports.prototype.getTags = function() {
    return this['tags'];
  }

  /**
   * @param {Array.<Number>} tags
   */
  exports.prototype.setTags = function(tags) {
    this['tags'] = tags;
  }


  /**
   * @return {Array.<Number>}
   */
  exports.prototype.getPresenters = function() {
    return this['presenters'];
  }

  /**
   * @param {Array.<Number>} presenters
   */
  exports.prototype.setPresenters = function(presenters) {
    this['presenters'] = presenters;
  }



  return exports;
}));


