/**
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BroadcastRelationsGenre from './BroadcastRelationsGenre';
import BroadcastRelationsGroup from './BroadcastRelationsGroup';
import BroadcastRelationsModelType from './BroadcastRelationsModelType';
import Program from './Program';
import ProgramOutputOnly from './ProgramOutputOnly';
import ProgramRelations from './ProgramRelations';
import ProgramRelationsBlocks from './ProgramRelationsBlocks';
import ProgramRelationsBroadcasts from './ProgramRelationsBroadcasts';
import ProgramRelationsItems from './ProgramRelationsItems';
import ProgramRelationsPresenters from './ProgramRelationsPresenters';
import ProgramRelationsTags from './ProgramRelationsTags';

/**
 * The ProgramResult model module.
 * @module models/ProgramResult
 * @version 2.0
 */
class ProgramResult {
    /**
     * Constructs a new <code>ProgramResult</code>.
     * @alias module:models/ProgramResult
     * @implements module:models/ProgramOutputOnly
     * @implements module:models/Program
     * @implements module:models/ProgramRelations
     * @param id {Number} 
     * @param modelTypeId {Number} 
     * @param title {String} 
     */
    constructor(id, modelTypeId, title) { 
        ProgramOutputOnly.initialize(this, id);Program.initialize(this, modelTypeId, title);ProgramRelations.initialize(this);
        ProgramResult.initialize(this, id, modelTypeId, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, modelTypeId, title) { 
        obj['id'] = id;
        obj['model_type_id'] = modelTypeId;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>ProgramResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/ProgramResult} obj Optional instance to populate.
     * @return {module:models/ProgramResult} The populated <code>ProgramResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProgramResult();
            ProgramOutputOnly.constructFromObject(data, obj);
            Program.constructFromObject(data, obj);
            ProgramRelations.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('_external_station_id')) {
                obj['_external_station_id'] = ApiClient.convertToType(data['_external_station_id'], 'Number');
            }
            if (data.hasOwnProperty('model_type_id')) {
                obj['model_type_id'] = ApiClient.convertToType(data['model_type_id'], 'Number');
            }
            if (data.hasOwnProperty('field_values')) {
                obj['field_values'] = ApiClient.convertToType(data['field_values'], Object);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('disabled')) {
                obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('genre_id')) {
                obj['genre_id'] = ApiClient.convertToType(data['genre_id'], 'Number');
            }
            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('short_name')) {
                obj['short_name'] = ApiClient.convertToType(data['short_name'], 'String');
            }
            if (data.hasOwnProperty('medium_name')) {
                obj['medium_name'] = ApiClient.convertToType(data['medium_name'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('recommended')) {
                obj['recommended'] = ApiClient.convertToType(data['recommended'], 'Boolean');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('pty_code_id')) {
                obj['pty_code_id'] = ApiClient.convertToType(data['pty_code_id'], 'Number');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = BroadcastRelationsGenre.constructFromObject(data['genre']);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ProgramRelationsItems.constructFromObject(data['items']);
            }
            if (data.hasOwnProperty('blocks')) {
                obj['blocks'] = ProgramRelationsBlocks.constructFromObject(data['blocks']);
            }
            if (data.hasOwnProperty('broadcasts')) {
                obj['broadcasts'] = ProgramRelationsBroadcasts.constructFromObject(data['broadcasts']);
            }
            if (data.hasOwnProperty('presenters')) {
                obj['presenters'] = ProgramRelationsPresenters.constructFromObject(data['presenters']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ProgramRelationsTags.constructFromObject(data['tags']);
            }
            if (data.hasOwnProperty('model_type')) {
                obj['model_type'] = BroadcastRelationsModelType.constructFromObject(data['model_type']);
            }
            if (data.hasOwnProperty('group')) {
                obj['group'] = BroadcastRelationsGroup.constructFromObject(data['group']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProgramResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProgramResult</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProgramResult.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['short_name'] && !(typeof data['short_name'] === 'string' || data['short_name'] instanceof String)) {
            throw new Error("Expected the field `short_name` to be a primitive type in the JSON string but got " + data['short_name']);
        }
        // ensure the json data is a string
        if (data['medium_name'] && !(typeof data['medium_name'] === 'string' || data['medium_name'] instanceof String)) {
            throw new Error("Expected the field `medium_name` to be a primitive type in the JSON string but got " + data['medium_name']);
        }
        // ensure the json data is a string
        if (data['website'] && !(typeof data['website'] === 'string' || data['website'] instanceof String)) {
            throw new Error("Expected the field `website` to be a primitive type in the JSON string but got " + data['website']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }
        // validate the optional field `genre`
        if (data['genre']) { // data not null
          BroadcastRelationsGenre.validateJSON(data['genre']);
        }
        // validate the optional field `items`
        if (data['items']) { // data not null
          ProgramRelationsItems.validateJSON(data['items']);
        }
        // validate the optional field `blocks`
        if (data['blocks']) { // data not null
          ProgramRelationsBlocks.validateJSON(data['blocks']);
        }
        // validate the optional field `broadcasts`
        if (data['broadcasts']) { // data not null
          ProgramRelationsBroadcasts.validateJSON(data['broadcasts']);
        }
        // validate the optional field `presenters`
        if (data['presenters']) { // data not null
          ProgramRelationsPresenters.validateJSON(data['presenters']);
        }
        // validate the optional field `tags`
        if (data['tags']) { // data not null
          ProgramRelationsTags.validateJSON(data['tags']);
        }
        // validate the optional field `model_type`
        if (data['model_type']) { // data not null
          BroadcastRelationsModelType.validateJSON(data['model_type']);
        }
        // validate the optional field `group`
        if (data['group']) { // data not null
          BroadcastRelationsGroup.validateJSON(data['group']);
        }

        return true;
    }

/**
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {Number} id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {Date}
     */
    getUpdatedAt() {
        return this.updated_at;
    }

    /**
     * @param {Date} updatedAt
     */
    setUpdatedAt(updatedAt) {
        this['updated_at'] = updatedAt;
    }
/**
     * @return {Date}
     */
    getCreatedAt() {
        return this.created_at;
    }

    /**
     * @param {Date} createdAt
     */
    setCreatedAt(createdAt) {
        this['created_at'] = createdAt;
    }
/**
     * @return {Date}
     */
    getDeletedAt() {
        return this.deleted_at;
    }

    /**
     * @param {Date} deletedAt
     */
    setDeletedAt(deletedAt) {
        this['deleted_at'] = deletedAt;
    }
/**
     * @return {Number}
     */
    getExternalStationId() {
        return this._external_station_id;
    }

    /**
     * @param {Number} externalStationId
     */
    setExternalStationId(externalStationId) {
        this['_external_station_id'] = externalStationId;
    }
/**
     * @return {Number}
     */
    getModelTypeId() {
        return this.model_type_id;
    }

    /**
     * @param {Number} modelTypeId
     */
    setModelTypeId(modelTypeId) {
        this['model_type_id'] = modelTypeId;
    }
/**
     * @return {Object}
     */
    getFieldValues() {
        return this.field_values;
    }

    /**
     * @param {Object} fieldValues
     */
    setFieldValues(fieldValues) {
        this['field_values'] = fieldValues;
    }
/**
     * @return {String}
     */
    getTitle() {
        return this.title;
    }

    /**
     * @param {String} title
     */
    setTitle(title) {
        this['title'] = title;
    }
/**
     * @return {Boolean}
     */
    getDisabled() {
        return this.disabled;
    }

    /**
     * @param {Boolean} disabled
     */
    setDisabled(disabled) {
        this['disabled'] = disabled;
    }
/**
     * @return {Number}
     */
    getGenreId() {
        return this.genre_id;
    }

    /**
     * @param {Number} genreId
     */
    setGenreId(genreId) {
        this['genre_id'] = genreId;
    }
/**
     * @return {Number}
     */
    getGroupId() {
        return this.group_id;
    }

    /**
     * @param {Number} groupId
     */
    setGroupId(groupId) {
        this['group_id'] = groupId;
    }
/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {String}
     */
    getShortName() {
        return this.short_name;
    }

    /**
     * @param {String} shortName
     */
    setShortName(shortName) {
        this['short_name'] = shortName;
    }
/**
     * @return {String}
     */
    getMediumName() {
        return this.medium_name;
    }

    /**
     * @param {String} mediumName
     */
    setMediumName(mediumName) {
        this['medium_name'] = mediumName;
    }
/**
     * @return {String}
     */
    getWebsite() {
        return this.website;
    }

    /**
     * @param {String} website
     */
    setWebsite(website) {
        this['website'] = website;
    }
/**
     * @return {String}
     */
    getEmail() {
        return this.email;
    }

    /**
     * @param {String} email
     */
    setEmail(email) {
        this['email'] = email;
    }
/**
     * @return {Boolean}
     */
    getRecommended() {
        return this.recommended;
    }

    /**
     * @param {Boolean} recommended
     */
    setRecommended(recommended) {
        this['recommended'] = recommended;
    }
/**
     * @return {String}
     */
    getLanguage() {
        return this.language;
    }

    /**
     * @param {String} language
     */
    setLanguage(language) {
        this['language'] = language;
    }
/**
     * @return {Number}
     */
    getPtyCodeId() {
        return this.pty_code_id;
    }

    /**
     * @param {Number} ptyCodeId
     */
    setPtyCodeId(ptyCodeId) {
        this['pty_code_id'] = ptyCodeId;
    }
/**
     * @return {module:models/BroadcastRelationsGenre}
     */
    getGenre() {
        return this.genre;
    }

    /**
     * @param {module:models/BroadcastRelationsGenre} genre
     */
    setGenre(genre) {
        this['genre'] = genre;
    }
/**
     * @return {module:models/ProgramRelationsItems}
     */
    getItems() {
        return this.items;
    }

    /**
     * @param {module:models/ProgramRelationsItems} items
     */
    setItems(items) {
        this['items'] = items;
    }
/**
     * @return {module:models/ProgramRelationsBlocks}
     */
    getBlocks() {
        return this.blocks;
    }

    /**
     * @param {module:models/ProgramRelationsBlocks} blocks
     */
    setBlocks(blocks) {
        this['blocks'] = blocks;
    }
/**
     * @return {module:models/ProgramRelationsBroadcasts}
     */
    getBroadcasts() {
        return this.broadcasts;
    }

    /**
     * @param {module:models/ProgramRelationsBroadcasts} broadcasts
     */
    setBroadcasts(broadcasts) {
        this['broadcasts'] = broadcasts;
    }
/**
     * @return {module:models/ProgramRelationsPresenters}
     */
    getPresenters() {
        return this.presenters;
    }

    /**
     * @param {module:models/ProgramRelationsPresenters} presenters
     */
    setPresenters(presenters) {
        this['presenters'] = presenters;
    }
/**
     * @return {module:models/ProgramRelationsTags}
     */
    getTags() {
        return this.tags;
    }

    /**
     * @param {module:models/ProgramRelationsTags} tags
     */
    setTags(tags) {
        this['tags'] = tags;
    }
/**
     * @return {module:models/BroadcastRelationsModelType}
     */
    getModelType() {
        return this.model_type;
    }

    /**
     * @param {module:models/BroadcastRelationsModelType} modelType
     */
    setModelType(modelType) {
        this['model_type'] = modelType;
    }
/**
     * @return {module:models/BroadcastRelationsGroup}
     */
    getGroup() {
        return this.group;
    }

    /**
     * @param {module:models/BroadcastRelationsGroup} group
     */
    setGroup(group) {
        this['group'] = group;
    }

}

ProgramResult.RequiredProperties = ["id", "model_type_id", "title"];

/**
 * @member {Number} id
 */
ProgramResult.prototype['id'] = undefined;

/**
 * @member {Date} updated_at
 */
ProgramResult.prototype['updated_at'] = undefined;

/**
 * @member {Date} created_at
 */
ProgramResult.prototype['created_at'] = undefined;

/**
 * @member {Date} deleted_at
 */
ProgramResult.prototype['deleted_at'] = undefined;

/**
 * @member {Number} _external_station_id
 */
ProgramResult.prototype['_external_station_id'] = undefined;

/**
 * @member {Number} model_type_id
 */
ProgramResult.prototype['model_type_id'] = undefined;

/**
 * @member {Object} field_values
 */
ProgramResult.prototype['field_values'] = undefined;

/**
 * @member {String} title
 */
ProgramResult.prototype['title'] = undefined;

/**
 * @member {Boolean} disabled
 */
ProgramResult.prototype['disabled'] = undefined;

/**
 * @member {Number} genre_id
 */
ProgramResult.prototype['genre_id'] = undefined;

/**
 * @member {Number} group_id
 */
ProgramResult.prototype['group_id'] = undefined;

/**
 * @member {String} description
 */
ProgramResult.prototype['description'] = undefined;

/**
 * @member {String} short_name
 */
ProgramResult.prototype['short_name'] = undefined;

/**
 * @member {String} medium_name
 */
ProgramResult.prototype['medium_name'] = undefined;

/**
 * @member {String} website
 */
ProgramResult.prototype['website'] = undefined;

/**
 * @member {String} email
 */
ProgramResult.prototype['email'] = undefined;

/**
 * @member {Boolean} recommended
 */
ProgramResult.prototype['recommended'] = undefined;

/**
 * @member {String} language
 */
ProgramResult.prototype['language'] = undefined;

/**
 * @member {Number} pty_code_id
 */
ProgramResult.prototype['pty_code_id'] = undefined;

/**
 * @member {module:models/BroadcastRelationsGenre} genre
 */
ProgramResult.prototype['genre'] = undefined;

/**
 * @member {module:models/ProgramRelationsItems} items
 */
ProgramResult.prototype['items'] = undefined;

/**
 * @member {module:models/ProgramRelationsBlocks} blocks
 */
ProgramResult.prototype['blocks'] = undefined;

/**
 * @member {module:models/ProgramRelationsBroadcasts} broadcasts
 */
ProgramResult.prototype['broadcasts'] = undefined;

/**
 * @member {module:models/ProgramRelationsPresenters} presenters
 */
ProgramResult.prototype['presenters'] = undefined;

/**
 * @member {module:models/ProgramRelationsTags} tags
 */
ProgramResult.prototype['tags'] = undefined;

/**
 * @member {module:models/BroadcastRelationsModelType} model_type
 */
ProgramResult.prototype['model_type'] = undefined;

/**
 * @member {module:models/BroadcastRelationsGroup} group
 */
ProgramResult.prototype['group'] = undefined;


// Implement ProgramOutputOnly interface:
/**
 * @member {Number} id
 */
ProgramOutputOnly.prototype['id'] = undefined;
/**
 * @member {Date} updated_at
 */
ProgramOutputOnly.prototype['updated_at'] = undefined;
/**
 * @member {Date} created_at
 */
ProgramOutputOnly.prototype['created_at'] = undefined;
/**
 * @member {Date} deleted_at
 */
ProgramOutputOnly.prototype['deleted_at'] = undefined;
/**
 * @member {Number} _external_station_id
 */
ProgramOutputOnly.prototype['_external_station_id'] = undefined;
// Implement Program interface:
/**
 * @member {Number} model_type_id
 */
Program.prototype['model_type_id'] = undefined;
/**
 * @member {Object} field_values
 */
Program.prototype['field_values'] = undefined;
/**
 * @member {String} title
 */
Program.prototype['title'] = undefined;
/**
 * @member {Boolean} disabled
 */
Program.prototype['disabled'] = undefined;
/**
 * @member {Number} genre_id
 */
Program.prototype['genre_id'] = undefined;
/**
 * @member {Number} group_id
 */
Program.prototype['group_id'] = undefined;
/**
 * @member {String} description
 */
Program.prototype['description'] = undefined;
/**
 * @member {String} short_name
 */
Program.prototype['short_name'] = undefined;
/**
 * @member {String} medium_name
 */
Program.prototype['medium_name'] = undefined;
/**
 * @member {String} website
 */
Program.prototype['website'] = undefined;
/**
 * @member {String} email
 */
Program.prototype['email'] = undefined;
/**
 * @member {Boolean} recommended
 */
Program.prototype['recommended'] = undefined;
/**
 * @member {String} language
 */
Program.prototype['language'] = undefined;
/**
 * @member {Number} pty_code_id
 */
Program.prototype['pty_code_id'] = undefined;
// Implement ProgramRelations interface:
/**
 * @member {module:models/BroadcastRelationsGenre} genre
 */
ProgramRelations.prototype['genre'] = undefined;
/**
 * @member {module:models/ProgramRelationsItems} items
 */
ProgramRelations.prototype['items'] = undefined;
/**
 * @member {module:models/ProgramRelationsBlocks} blocks
 */
ProgramRelations.prototype['blocks'] = undefined;
/**
 * @member {module:models/ProgramRelationsBroadcasts} broadcasts
 */
ProgramRelations.prototype['broadcasts'] = undefined;
/**
 * @member {module:models/ProgramRelationsPresenters} presenters
 */
ProgramRelations.prototype['presenters'] = undefined;
/**
 * @member {module:models/ProgramRelationsTags} tags
 */
ProgramRelations.prototype['tags'] = undefined;
/**
 * @member {module:models/BroadcastRelationsModelType} model_type
 */
ProgramRelations.prototype['model_type'] = undefined;
/**
 * @member {module:models/BroadcastRelationsGroup} group
 */
ProgramRelations.prototype['group'] = undefined;




export default ProgramResult;

