/**
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'models/StationResultStation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StationResultStation'));
  } else {
    // Browser globals (root is window)
    if (!root.radiomanager) {
      root.radiomanager = {};
    }
    root.radiomanager.StationResult = factory(root.radiomanager.ApiClient, root.radiomanager.StationResultStation);
  }
}(this, function(ApiClient, StationResultStation) {
  'use strict';



  /**
   * The StationResult model module.
   * @module models/StationResult
   * @version 2.0
   */

  /**
   * Constructs a new <code>StationResult</code>.
   * @alias module:models/StationResult
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>StationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:models/StationResult} obj Optional instance to populate.
   * @return {module:models/StationResult} The populated <code>StationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('station')) {
        obj['station'] = StationResultStation.constructFromObject(data['station']);
      }
    }
    return obj;
  }

  /**
   * @member {module:models/StationResultStation} station
   */
  exports.prototype['station'] = undefined;


  /**
   * @return {module:models/StationResultStation}
   */
  exports.prototype.getStation = function() {
    return this['station'];
  }

  /**
   * @param {module:models/StationResultStation} station
   */
  exports.prototype.setStation = function(station) {
    this['station'] = station;
  }



  return exports;
}));


