/**
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnusedBooleanParameter model module.
 * @module models/UnusedBooleanParameter
 * @version 2.0
 */
class UnusedBooleanParameter {
    /**
     * Constructs a new <code>UnusedBooleanParameter</code>.
     * @alias module:models/UnusedBooleanParameter
     * @param {(module:models/Boolean|module:models/Number)} instance The actual instance to initialize UnusedBooleanParameter.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate array of integer
            if (!(typeof instance === 'number' && instance % 1 === 0)) {
                throw new Error("Invalid array items. Must be integer. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Number
            errorMessages.push("Failed to construct Number: " + err)
        }

        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Boolean
            errorMessages.push("Failed to construct Boolean: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `UnusedBooleanParameter` with oneOf schemas Boolean, Number. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `UnusedBooleanParameter` with oneOf schemas Boolean, Number. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>UnusedBooleanParameter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/UnusedBooleanParameter} obj Optional instance to populate.
     * @return {module:models/UnusedBooleanParameter} The populated <code>UnusedBooleanParameter</code> instance.
     */
    static constructFromObject(data, obj) {
        return new UnusedBooleanParameter(data);
    }

    /**
     * Gets the actaul instance, which can be <code>Boolean</code>, <code>Number</code>.
     * @return {(module:models/Boolean|module:models/Number)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actaul instance, which can be <code>Boolean</code>, <code>Number</code>.
     * @param {(module:models/Boolean|module:models/Number)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = UnusedBooleanParameter.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual intance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of UnusedBooleanParameter from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:models/UnusedBooleanParameter} An instance of UnusedBooleanParameter.
     */
    static fromJSON = function(json_string){
        return UnusedBooleanParameter.constructFromObject(JSON.parse(json_string));
    }
}


UnusedBooleanParameter.OneOf = ["Boolean", "Number"];

export default UnusedBooleanParameter;

